services:
  ripplechat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8080:8080"
    volumes:
      - vcpkg_cache:/vcpkg/downloads

volumes:
  vcpkg_cache: